baseURL = "http://beta.gingerdolls.dk/"
languageCode = "da-dk"
title = "GingerDolls"
theme = "ginger-hugo-theme"
defaultContentLanguage = "da"
enableGitInfo = true

[params]
  CloudinaryBaseURL = "https://res.cloudinary.com/dw0rj924o/image/upload"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[languages]
  [languages.da]
  [languages.en]